model_name: "ResNet"
field_solution_map: False

encoder: {
name: "resnet18",
hidden_channels: [64, 128, 256, 512]
}

decoder: {
name: "explicit_mlp",
hidden_channels: [512,512, 512, 512, 512, 512]
}

dataset_keys: ["bead_patterns", "z_vel_mean_sq", "sample_mat"]
