model_name: "FNO"
field_solution_map: True
lr: 0.001

hidden_channels: 128
n_layers: 8
n_modes: 32

tfno: False
film: True

dataset_keys: ["bead_patterns", "z_abs_velocity", "z_vel_mean_sq", "sample_mat"]
