model_name: "FNO"
field_solution_map: True
lr: 0.001

hidden_channels: 128
n_layers: 4
n_modes: 16

tfno: False
film: True

dataset_keys: ["bead_patterns", "z_abs_velocity", "z_vel_mean_sq", "sample_mat"]
