model_name: "FNO"
velocity_field: True
lr: 0.001

hidden_channels: 128
n_layers: 8
n_modes: 32

tfno: False
film: True

dataset_keys: ["bead_patterns", "z_vel_abs", "z_vel_mean_sq", "phy_para", "frequencies"]
