optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0005,
  weight_decay : 0.00005,
  betas: [0.9, 0.99]
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 500,
    initial_epochs: 50,
    lr_min: 0.00001
}}


validation_frequency: 5
epochs : 500
gradient_clip: 100
report_wasserstein: True
random_split: True
split_ratio: [0.9, 0.1]

data_path_ref: "vibrating_plates_data/V5000_2000_lower_res.h5"

n_frequencies: 300
max_frequency: 250


data_paths: [
            "vibrating_plates_data/V5000_2000_lower_res.h5",
            "vibrating_plates_data/V5000_3000_lower_res.h5"
            ]
data_paths_test: ["vibrating_plates_data/V5000_1000__test_lower_res.h5"]

dataset_keys: ["bead_patterns", "z_abs_velocity", "z_vel_mean_sq", "sample_mat"]

dataset_class: "hdf5"
conditional: False

filter_dataset: True
filter_orientation: "larger"
filter_type: "bead_ratio"